[package]
name = "algorithmik3"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "problem1"
path = "src/bin/problem1.rs"

[[bin]]
name = "problem2"
path = "src/bin/problem2.rs"

